// Code generated by protoc-gen-go. DO NOT EDIT.
// source: issuer.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListIssuerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListIssuerRequest) Reset()         { *m = ListIssuerRequest{} }
func (m *ListIssuerRequest) String() string { return proto.CompactTextString(m) }
func (*ListIssuerRequest) ProtoMessage()    {}
func (*ListIssuerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8d83c9b614651f, []int{0}
}

func (m *ListIssuerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIssuerRequest.Unmarshal(m, b)
}
func (m *ListIssuerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIssuerRequest.Marshal(b, m, deterministic)
}
func (m *ListIssuerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIssuerRequest.Merge(m, src)
}
func (m *ListIssuerRequest) XXX_Size() int {
	return xxx_messageInfo_ListIssuerRequest.Size(m)
}
func (m *ListIssuerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIssuerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListIssuerRequest proto.InternalMessageInfo

type ListIssuerCollection struct {
	Field                []*IssuerRequest `protobuf:"bytes,1,rep,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListIssuerCollection) Reset()         { *m = ListIssuerCollection{} }
func (m *ListIssuerCollection) String() string { return proto.CompactTextString(m) }
func (*ListIssuerCollection) ProtoMessage()    {}
func (*ListIssuerCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8d83c9b614651f, []int{1}
}

func (m *ListIssuerCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIssuerCollection.Unmarshal(m, b)
}
func (m *ListIssuerCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIssuerCollection.Marshal(b, m, deterministic)
}
func (m *ListIssuerCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIssuerCollection.Merge(m, src)
}
func (m *ListIssuerCollection) XXX_Size() int {
	return xxx_messageInfo_ListIssuerCollection.Size(m)
}
func (m *ListIssuerCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIssuerCollection.DiscardUnknown(m)
}

var xxx_messageInfo_ListIssuerCollection proto.InternalMessageInfo

func (m *ListIssuerCollection) GetField() []*IssuerRequest {
	if m != nil {
		return m.Field
	}
	return nil
}

type IssuerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuerResponse) Reset()         { *m = IssuerResponse{} }
func (m *IssuerResponse) String() string { return proto.CompactTextString(m) }
func (*IssuerResponse) ProtoMessage()    {}
func (*IssuerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8d83c9b614651f, []int{2}
}

func (m *IssuerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuerResponse.Unmarshal(m, b)
}
func (m *IssuerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuerResponse.Marshal(b, m, deterministic)
}
func (m *IssuerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuerResponse.Merge(m, src)
}
func (m *IssuerResponse) XXX_Size() int {
	return xxx_messageInfo_IssuerResponse.Size(m)
}
func (m *IssuerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IssuerResponse proto.InternalMessageInfo

type IssuerRequest struct {
	// Types that are valid to be assigned to DnsSolvers:
	//	*IssuerRequest_AcmeIssuer
	//	*IssuerRequest_SelfSignedIssuer
	DnsSolvers           isIssuerRequest_DnsSolvers `protobuf_oneof:"dns_solvers"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *IssuerRequest) Reset()         { *m = IssuerRequest{} }
func (m *IssuerRequest) String() string { return proto.CompactTextString(m) }
func (*IssuerRequest) ProtoMessage()    {}
func (*IssuerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8d83c9b614651f, []int{3}
}

func (m *IssuerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuerRequest.Unmarshal(m, b)
}
func (m *IssuerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuerRequest.Marshal(b, m, deterministic)
}
func (m *IssuerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuerRequest.Merge(m, src)
}
func (m *IssuerRequest) XXX_Size() int {
	return xxx_messageInfo_IssuerRequest.Size(m)
}
func (m *IssuerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IssuerRequest proto.InternalMessageInfo

type isIssuerRequest_DnsSolvers interface {
	isIssuerRequest_DnsSolvers()
}

type IssuerRequest_AcmeIssuer struct {
	AcmeIssuer *LetsEncryptIssuerRequest `protobuf:"bytes,1,opt,name=acme_issuer,json=acmeIssuer,proto3,oneof"`
}

type IssuerRequest_SelfSignedIssuer struct {
	SelfSignedIssuer *SelfSignedIssuerRequest `protobuf:"bytes,2,opt,name=self_signed_issuer,json=selfSignedIssuer,proto3,oneof"`
}

func (*IssuerRequest_AcmeIssuer) isIssuerRequest_DnsSolvers() {}

func (*IssuerRequest_SelfSignedIssuer) isIssuerRequest_DnsSolvers() {}

func (m *IssuerRequest) GetDnsSolvers() isIssuerRequest_DnsSolvers {
	if m != nil {
		return m.DnsSolvers
	}
	return nil
}

func (m *IssuerRequest) GetAcmeIssuer() *LetsEncryptIssuerRequest {
	if x, ok := m.GetDnsSolvers().(*IssuerRequest_AcmeIssuer); ok {
		return x.AcmeIssuer
	}
	return nil
}

func (m *IssuerRequest) GetSelfSignedIssuer() *SelfSignedIssuerRequest {
	if x, ok := m.GetDnsSolvers().(*IssuerRequest_SelfSignedIssuer); ok {
		return x.SelfSignedIssuer
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IssuerRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IssuerRequest_AcmeIssuer)(nil),
		(*IssuerRequest_SelfSignedIssuer)(nil),
	}
}

type LetsEncryptIssuerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Server               string   `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Solver               *Solver  `protobuf:"bytes,4,opt,name=solver,proto3" json:"solver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LetsEncryptIssuerRequest) Reset()         { *m = LetsEncryptIssuerRequest{} }
func (m *LetsEncryptIssuerRequest) String() string { return proto.CompactTextString(m) }
func (*LetsEncryptIssuerRequest) ProtoMessage()    {}
func (*LetsEncryptIssuerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8d83c9b614651f, []int{4}
}

func (m *LetsEncryptIssuerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LetsEncryptIssuerRequest.Unmarshal(m, b)
}
func (m *LetsEncryptIssuerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LetsEncryptIssuerRequest.Marshal(b, m, deterministic)
}
func (m *LetsEncryptIssuerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LetsEncryptIssuerRequest.Merge(m, src)
}
func (m *LetsEncryptIssuerRequest) XXX_Size() int {
	return xxx_messageInfo_LetsEncryptIssuerRequest.Size(m)
}
func (m *LetsEncryptIssuerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LetsEncryptIssuerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LetsEncryptIssuerRequest proto.InternalMessageInfo

func (m *LetsEncryptIssuerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LetsEncryptIssuerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LetsEncryptIssuerRequest) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *LetsEncryptIssuerRequest) GetSolver() *Solver {
	if m != nil {
		return m.Solver
	}
	return nil
}

type Solver struct {
	// Types that are valid to be assigned to DnsSolvers:
	//	*Solver_CloudFlareSolver
	//	*Solver_GoogleCloudSolver
	DnsSolvers           isSolver_DnsSolvers `protobuf_oneof:"dns_solvers"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Solver) Reset()         { *m = Solver{} }
func (m *Solver) String() string { return proto.CompactTextString(m) }
func (*Solver) ProtoMessage()    {}
func (*Solver) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8d83c9b614651f, []int{5}
}

func (m *Solver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Solver.Unmarshal(m, b)
}
func (m *Solver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Solver.Marshal(b, m, deterministic)
}
func (m *Solver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Solver.Merge(m, src)
}
func (m *Solver) XXX_Size() int {
	return xxx_messageInfo_Solver.Size(m)
}
func (m *Solver) XXX_DiscardUnknown() {
	xxx_messageInfo_Solver.DiscardUnknown(m)
}

var xxx_messageInfo_Solver proto.InternalMessageInfo

type isSolver_DnsSolvers interface {
	isSolver_DnsSolvers()
}

type Solver_CloudFlareSolver struct {
	CloudFlareSolver *CloudFlareSolver `protobuf:"bytes,1,opt,name=cloud_flare_solver,json=cloudFlareSolver,proto3,oneof"`
}

type Solver_GoogleCloudSolver struct {
	GoogleCloudSolver *GoogleCloudSolver `protobuf:"bytes,2,opt,name=google_cloud_solver,json=googleCloudSolver,proto3,oneof"`
}

func (*Solver_CloudFlareSolver) isSolver_DnsSolvers() {}

func (*Solver_GoogleCloudSolver) isSolver_DnsSolvers() {}

func (m *Solver) GetDnsSolvers() isSolver_DnsSolvers {
	if m != nil {
		return m.DnsSolvers
	}
	return nil
}

func (m *Solver) GetCloudFlareSolver() *CloudFlareSolver {
	if x, ok := m.GetDnsSolvers().(*Solver_CloudFlareSolver); ok {
		return x.CloudFlareSolver
	}
	return nil
}

func (m *Solver) GetGoogleCloudSolver() *GoogleCloudSolver {
	if x, ok := m.GetDnsSolvers().(*Solver_GoogleCloudSolver); ok {
		return x.GoogleCloudSolver
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Solver) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Solver_CloudFlareSolver)(nil),
		(*Solver_GoogleCloudSolver)(nil),
	}
}

type CloudFlareSolver struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Apikey               string   `protobuf:"bytes,2,opt,name=apikey,proto3" json:"apikey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudFlareSolver) Reset()         { *m = CloudFlareSolver{} }
func (m *CloudFlareSolver) String() string { return proto.CompactTextString(m) }
func (*CloudFlareSolver) ProtoMessage()    {}
func (*CloudFlareSolver) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8d83c9b614651f, []int{6}
}

func (m *CloudFlareSolver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudFlareSolver.Unmarshal(m, b)
}
func (m *CloudFlareSolver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudFlareSolver.Marshal(b, m, deterministic)
}
func (m *CloudFlareSolver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudFlareSolver.Merge(m, src)
}
func (m *CloudFlareSolver) XXX_Size() int {
	return xxx_messageInfo_CloudFlareSolver.Size(m)
}
func (m *CloudFlareSolver) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudFlareSolver.DiscardUnknown(m)
}

var xxx_messageInfo_CloudFlareSolver proto.InternalMessageInfo

func (m *CloudFlareSolver) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CloudFlareSolver) GetApikey() string {
	if m != nil {
		return m.Apikey
	}
	return ""
}

type GoogleCloudSolver struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Sa                   []byte   `protobuf:"bytes,2,opt,name=sa,proto3" json:"sa,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleCloudSolver) Reset()         { *m = GoogleCloudSolver{} }
func (m *GoogleCloudSolver) String() string { return proto.CompactTextString(m) }
func (*GoogleCloudSolver) ProtoMessage()    {}
func (*GoogleCloudSolver) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8d83c9b614651f, []int{7}
}

func (m *GoogleCloudSolver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleCloudSolver.Unmarshal(m, b)
}
func (m *GoogleCloudSolver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleCloudSolver.Marshal(b, m, deterministic)
}
func (m *GoogleCloudSolver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleCloudSolver.Merge(m, src)
}
func (m *GoogleCloudSolver) XXX_Size() int {
	return xxx_messageInfo_GoogleCloudSolver.Size(m)
}
func (m *GoogleCloudSolver) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleCloudSolver.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleCloudSolver proto.InternalMessageInfo

func (m *GoogleCloudSolver) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GoogleCloudSolver) GetSa() []byte {
	if m != nil {
		return m.Sa
	}
	return nil
}

type SelfSignedIssuerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfSignedIssuerRequest) Reset()         { *m = SelfSignedIssuerRequest{} }
func (m *SelfSignedIssuerRequest) String() string { return proto.CompactTextString(m) }
func (*SelfSignedIssuerRequest) ProtoMessage()    {}
func (*SelfSignedIssuerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8d83c9b614651f, []int{8}
}

func (m *SelfSignedIssuerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfSignedIssuerRequest.Unmarshal(m, b)
}
func (m *SelfSignedIssuerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfSignedIssuerRequest.Marshal(b, m, deterministic)
}
func (m *SelfSignedIssuerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfSignedIssuerRequest.Merge(m, src)
}
func (m *SelfSignedIssuerRequest) XXX_Size() int {
	return xxx_messageInfo_SelfSignedIssuerRequest.Size(m)
}
func (m *SelfSignedIssuerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfSignedIssuerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelfSignedIssuerRequest proto.InternalMessageInfo

func (m *SelfSignedIssuerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// A request for ping
type PingRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8d83c9b614651f, []int{9}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// A response for ping
type PingResponse struct {
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8d83c9b614651f, []int{10}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ListIssuerRequest)(nil), "api.ListIssuerRequest")
	proto.RegisterType((*ListIssuerCollection)(nil), "api.ListIssuerCollection")
	proto.RegisterType((*IssuerResponse)(nil), "api.IssuerResponse")
	proto.RegisterType((*IssuerRequest)(nil), "api.IssuerRequest")
	proto.RegisterType((*LetsEncryptIssuerRequest)(nil), "api.LetsEncryptIssuerRequest")
	proto.RegisterType((*Solver)(nil), "api.Solver")
	proto.RegisterType((*CloudFlareSolver)(nil), "api.CloudFlareSolver")
	proto.RegisterType((*GoogleCloudSolver)(nil), "api.GoogleCloudSolver")
	proto.RegisterType((*SelfSignedIssuerRequest)(nil), "api.SelfSignedIssuerRequest")
	proto.RegisterType((*PingRequest)(nil), "api.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "api.PingResponse")
}

func init() { proto.RegisterFile("issuer.proto", fileDescriptor_8e8d83c9b614651f) }

var fileDescriptor_8e8d83c9b614651f = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x8d, 0x81, 0x20, 0x65, 0x4c, 0x22, 0x33, 0xa4, 0xa9, 0x8b, 0x5a, 0x15, 0x6d, 0x2f, 0x5c,
	0xc2, 0x81, 0x9e, 0x72, 0x43, 0x41, 0x69, 0x53, 0x89, 0x43, 0x65, 0x3e, 0xc0, 0xda, 0x9a, 0xc1,
	0x5a, 0x75, 0xb1, 0x5d, 0xaf, 0x41, 0xca, 0xb1, 0x7f, 0xd3, 0x53, 0xff, 0xa0, 0xff, 0x56, 0x79,
	0xd6, 0x86, 0xe0, 0x84, 0x9b, 0xf7, 0xbd, 0x37, 0x6f, 0xdf, 0xce, 0xee, 0x18, 0x7a, 0xca, 0x98,
	0x2d, 0xe5, 0x93, 0x2c, 0x4f, 0x8b, 0x14, 0xdb, 0x32, 0x53, 0x62, 0x00, 0xfd, 0x85, 0x32, 0xc5,
	0x37, 0x26, 0x02, 0xfa, 0xb5, 0x25, 0x53, 0x88, 0x19, 0x5c, 0x1f, 0xc0, 0x79, 0xaa, 0x35, 0x45,
	0x85, 0x4a, 0x13, 0x1c, 0xc3, 0xf9, 0x5a, 0x91, 0x5e, 0xf9, 0xce, 0xa8, 0x3d, 0x76, 0xa7, 0x38,
	0x91, 0x99, 0x9a, 0x1c, 0x95, 0x06, 0x56, 0x20, 0x3c, 0xb8, 0xaa, 0x71, 0x93, 0xa5, 0x89, 0x21,
	0xf1, 0xd7, 0x81, 0xcb, 0x23, 0x29, 0xce, 0xc0, 0x95, 0xd1, 0x86, 0x42, 0x1b, 0xca, 0x77, 0x46,
	0xce, 0xd8, 0x9d, 0x7e, 0x60, 0xcf, 0x05, 0x15, 0xe6, 0x21, 0x89, 0xf2, 0xa7, 0xec, 0x38, 0xd9,
	0xe3, 0x59, 0x00, 0x65, 0x8d, 0x05, 0x71, 0x01, 0x68, 0x48, 0xaf, 0x43, 0xa3, 0xe2, 0x84, 0x56,
	0xb5, 0x51, 0x8b, 0x8d, 0xde, 0xb3, 0xd1, 0x92, 0xf4, 0x7a, 0xc9, 0x6c, 0xd3, 0xc7, 0x33, 0x0d,
	0xea, 0xfe, 0x12, 0xdc, 0x55, 0x62, 0x42, 0x93, 0xea, 0x1d, 0xe5, 0x46, 0xfc, 0x76, 0xc0, 0x3f,
	0x95, 0x03, 0x11, 0x3a, 0x89, 0xdc, 0x10, 0x87, 0xbe, 0x08, 0xf8, 0x1b, 0xaf, 0xe1, 0x9c, 0x36,
	0x52, 0x69, 0x0e, 0x70, 0x11, 0xd8, 0x05, 0xde, 0x40, 0xd7, 0x50, 0xbe, 0xa3, 0xdc, 0x6f, 0x33,
	0x5c, 0xad, 0xf0, 0x13, 0x74, 0xed, 0x4e, 0x7e, 0x87, 0xf3, 0xba, 0x36, 0x2f, 0x43, 0x41, 0x45,
	0x89, 0x3f, 0x0e, 0x74, 0x2d, 0x84, 0x0f, 0x80, 0x91, 0x4e, 0xb7, 0xab, 0x70, 0xad, 0x65, 0x4e,
	0x55, 0xca, 0xaa, 0x69, 0x6f, 0xb8, 0x76, 0x5e, 0xd2, 0x5f, 0x4a, 0xd6, 0x96, 0x94, 0x87, 0x8c,
	0x1a, 0x18, 0x3e, 0xc2, 0x20, 0x4e, 0xd3, 0x58, 0x53, 0x68, 0xdd, 0x2a, 0x1f, 0xdb, 0xb3, 0x1b,
	0xf6, 0xf9, 0xca, 0x3c, 0xbb, 0xed, 0x8d, 0xfa, 0x71, 0x13, 0x6c, 0xb6, 0x6b, 0x06, 0x5e, 0x33,
	0xc0, 0xa1, 0x23, 0x4e, 0xa3, 0x23, 0x32, 0x53, 0x3f, 0xe9, 0xa9, 0x6a, 0x54, 0xb5, 0x12, 0x77,
	0xd0, 0x7f, 0xb1, 0xf5, 0x09, 0x8b, 0x2b, 0x68, 0x19, 0xc9, 0xe5, 0xbd, 0xa0, 0x65, 0xa4, 0xb8,
	0x85, 0xb7, 0x27, 0x6e, 0xfa, 0xb5, 0x9b, 0x12, 0x1f, 0xc1, 0xfd, 0xae, 0x92, 0xb8, 0x96, 0x78,
	0xd0, 0xde, 0x98, 0xb8, 0x52, 0x94, 0x9f, 0x62, 0x04, 0x3d, 0x2b, 0xb0, 0x8f, 0xb7, 0x56, 0xb4,
	0xf6, 0x8a, 0xe9, 0xbf, 0xfd, 0x73, 0x5e, 0x52, 0xbe, 0x53, 0x11, 0xe1, 0x1d, 0xf4, 0xe6, 0x39,
	0xc9, 0xa2, 0x7e, 0x9c, 0xaf, 0x4c, 0xc7, 0x70, 0x70, 0x84, 0x55, 0x93, 0x71, 0x86, 0xf7, 0xe0,
	0x1e, 0xe6, 0xcd, 0xa0, 0xbd, 0x86, 0x17, 0x63, 0x39, 0x7c, 0xd7, 0xc0, 0x0f, 0x93, 0x29, 0xce,
	0xf0, 0x16, 0x3a, 0x65, 0x64, 0xf4, 0x58, 0xf4, 0xec, 0x78, 0xc3, 0xfe, 0x33, 0xa4, 0xde, 0xf2,
	0x47, 0x97, 0xff, 0x01, 0x9f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x44, 0xd2, 0x7f, 0x13,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IssuerServiceClient is the client API for IssuerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IssuerServiceClient interface {
	CreateIssuer(ctx context.Context, in *IssuerRequest, opts ...grpc.CallOption) (*IssuerResponse, error)
	ListIssuers(ctx context.Context, in *ListIssuerRequest, opts ...grpc.CallOption) (*ListIssuerCollection, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type issuerServiceClient struct {
	cc *grpc.ClientConn
}

func NewIssuerServiceClient(cc *grpc.ClientConn) IssuerServiceClient {
	return &issuerServiceClient{cc}
}

func (c *issuerServiceClient) CreateIssuer(ctx context.Context, in *IssuerRequest, opts ...grpc.CallOption) (*IssuerResponse, error) {
	out := new(IssuerResponse)
	err := c.cc.Invoke(ctx, "/api.IssuerService/CreateIssuer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerServiceClient) ListIssuers(ctx context.Context, in *ListIssuerRequest, opts ...grpc.CallOption) (*ListIssuerCollection, error) {
	out := new(ListIssuerCollection)
	err := c.cc.Invoke(ctx, "/api.IssuerService/ListIssuers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issuerServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/api.IssuerService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssuerServiceServer is the server API for IssuerService service.
type IssuerServiceServer interface {
	CreateIssuer(context.Context, *IssuerRequest) (*IssuerResponse, error)
	ListIssuers(context.Context, *ListIssuerRequest) (*ListIssuerCollection, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

// UnimplementedIssuerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIssuerServiceServer struct {
}

func (*UnimplementedIssuerServiceServer) CreateIssuer(ctx context.Context, req *IssuerRequest) (*IssuerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIssuer not implemented")
}
func (*UnimplementedIssuerServiceServer) ListIssuers(ctx context.Context, req *ListIssuerRequest) (*ListIssuerCollection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIssuers not implemented")
}
func (*UnimplementedIssuerServiceServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterIssuerServiceServer(s *grpc.Server, srv IssuerServiceServer) {
	s.RegisterService(&_IssuerService_serviceDesc, srv)
}

func _IssuerService_CreateIssuer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssuerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServiceServer).CreateIssuer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IssuerService/CreateIssuer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServiceServer).CreateIssuer(ctx, req.(*IssuerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssuerService_ListIssuers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssuerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServiceServer).ListIssuers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IssuerService/ListIssuers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServiceServer).ListIssuers(ctx, req.(*ListIssuerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssuerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IssuerService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IssuerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.IssuerService",
	HandlerType: (*IssuerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIssuer",
			Handler:    _IssuerService_CreateIssuer_Handler,
		},
		{
			MethodName: "ListIssuers",
			Handler:    _IssuerService_ListIssuers_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _IssuerService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "issuer.proto",
}
